# fly.toml app configuration file generated for gauntlet-video-server on 2025-11-14T15:11:03-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gauntlet-gen-platform-v3'
primary_region = 'dfw'

[build]
  dockerfile = "Dockerfile.v3"

[env]
  DATA = '/data'
  PORT = '8080'
  ACCESS_TOKEN_EXPIRE_MINUTES = '7200'  # 5 days
  BASE_URL='https://gauntlet-gen-platform-v3.fly.dev'

[[mounts]]
  source = 'gen_platform_v3_data'
  destination = '/data'
  initial_size = '1GB'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/api/v3/health'

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
